name: athena
version: 0.1.0
status: preview
iac_type: terraform
dependencies:
  - governance/subscription
params:
  - name: athena_workgroup
    required: false
    default: primary
    type: string
    pattern: "^[a-zA-Z0-9_-]+$"
artifacts:
  - cfn-template.yaml
  - terraform/main.tf
