name: s3-csv
version: 0.1.0
status: ready
iac_type: terraform
dependencies:
  - governance/infrastructure
params:
  - name: bucket_name
    required: false
    type: string
  - name: quicksight_role_arn
    required: false
    type: string
  - name: csv_key
    required: true
    type: string
  - name: dataset_name
    required: false
    default: airline-revenue
